---
- hosts      : all
  remote_user: root
  tasks      :
    - name   : distribute switch image
      copy   :
        src  : ~/switch.tar
        dest : ~/switch.tar

    - name   : distribute ubuntu image
      copy   :
        src  : ~/ubuntu.tar
        dest : ~/ubuntu.tar

#    - name   : distribute debian image
#      copy   :
#        src  : ~/debian.tar.gz
#        dest : ~/debian.tar.gz

#    - name   : distribute master image
#      copy   :
#        src  : ~/ubuntu-hadoop-master.tar.gz
#        dest : ~/ubuntu-hadoop-master.tar.gz

#    - name   : distribute slave image
#      copy   :
#        src  : ~/ubuntu-hadoop-slave.tar.gz
#        dest : ~/ubuntu-hadoop-slave.tar.gz


#    - name   : distribute onos image
#      copy   :
#        src  : ~/ubuntu-onos-2.1.0.tar.gz
#        dest : ~/ubuntu-onos-2.1.0.tar.gz

- hosts      : all
  remote_user: root
  tasks      :
    - name   : create switch image
      command: docker load -i ~/switch.tar 

    - name   : create ubuntu18.04 image -- alias ubuntu
      command: docker load -i ~/ubuntu.tar
#    - name   : create debian10 image -- alias debian
#      command: lxc image import ~/debian.tar.gz --alias debian --public

#    - name   : create master image
#      command: lxc image import ~/ubuntu-hadoop-master.tar.gz --alias ubuntu-hadoop-master --public

#    - name   : create slave image
#      command: lxc image import ~/ubuntu-hadoop-slave.tar.gz --alias ubuntu-hadoop-slave --public

#    - name   : create onos image
#      command: lxc image import ~/ubuntu-onos-2.1.0.tar.gz --alias ubuntu-onos-2.1.0 --public


